### ISSUE TITLE
hang on connecting - how to troubleshoot?

### ISSUE THREAD

**Issue by anthonymobile** [tomas/rtop#4]
on OSX, can't seem to connect to any of various hosts, rtop just sits at the "-- connecting..." status. is there a log or any verbose/debugging options to see what's going on under the hood?

**Comment by anthonymobile** [comment]
last commit showing is still 28 april. did you push to master?

its confusing. im able to successfully ssh using the same machine w/ no issues.
e.g. this works w/ passwordless
`ssh -p 7307 anthony@192.168.1.200`
none of these do
`rtop -u anthony -p 7307 192.168.1.200`
`rtop -u anthony -p 7307 192.168.1.200 -k ~/.ssh/id_rsa`
`rtop -p 7307 anthony@192.168.1.200`

**Comment by tomas** [comment]
Yikes, you're right. I published without pulling first the latest changes on Github (that address that issue). Try again using version 0.4.6.

(And sorry for the goofyness, haha)

**Comment by anthonymobile** [comment]
i must be doing something really wrong as i am still getting 'all configured authentication methods failed' regardless of what hosts, keys, flags i use. i suspect a permissions problem somewhere but not sure where to look. sorry to bug you and thanks for the help

**Comment by tomas** [comment]
Are you able to ssh to the host(s) normally without any problems?

**Comment by anthonymobile** [comment]
yes. its only rtop. i could probably figure this out on my own if i could get some diagnostics but there's nothing in the syslog as far as i can see and rtop isnt saying much. any ideas?
